name: show_app
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"



dependencies:
  flutter:
    sdk: flutter

  ffi: ^1.1.2
  google_fonts: ^2.1.0
  shared_preferences: ^2.0.13
  flutter_slidable: ^0.6.0
  image_picker: ^0.8.1+4
  localstorage: ^4.0.0+1
  email_auth: ^0.0.1+4
  syncfusion_flutter_datepicker: ^19.3.47
  duration_picker: "^1.0.0"
  url_launcher: ^6.0.17
  step_progress_indicator: ^1.0.1
  flutter_datetime_picker: ^1.5.1
  octo_image: ^1.0.0+1
  progressive_image: ^2.0.0
  shimmer: ^2.0.0
  liquid_progress_indicator: ^0.4.0
  flutter_email_sender: ^5.0.2
  flutter_mailer: ^2.0.0
  flutter_downloader: ^1.7.0
  mailer: ^5.0.2
  multiselect_formfield: ^0.1.6
  pin_code_fields: ^7.2.0
  flutter_svg:
  dio: ^4.0.0
  get: ^4.3.8
  get_storage: ^2.0.3
  cupertino_icons: ^1.0.3
  cached_network_image: ^3.1.0
  chips_choice: ^2.0.1
  http: ^0.13.3
  adobe_xd: ^2.0.0+1
  mime: ^1.0.0
  file_picker: ^4.0.0
  responsive_builder: ^0.4.1
  syncfusion_flutter_calendar: ^19.2.48
  curved_navigation_bar: ^1.0.1
  multi_select_flutter: ^4.0.0
  flutter_multiselect: ^1.0.0
  smart_select: ^4.3.2
  sticky_headers: "^0.1.8"
  flutter_animated_button: ^2.0.0
  country_picker: ^2.0.7
  floating_bottom_navigation_bar: ^1.5.2
  flutter_calendar_carousel: ^2.0.3
  animated_splash_screen: ^1.1.0
  table_calendar: ^3.0.3
  flutter_staggered_grid_view: ^0.6.1
  image_cropper: ^1.5.0
  image_crop: ^0.4.0
  http_auth: ^1.0.1
  webview_flutter: ^3.0.1
  intl: ^0.17.0
  flutter_paypal:
  animated_text_kit: ^4.2.1
  device_info_plus: ^3.2.3
dev_dependencies:


flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
  fonts:
    - family: CustomIcon
      fonts:
        - asset: assets/fonts/Icons.ttf
    - family: CustomIcon1
      fonts:
        - asset: assets/fonts/Icons2.ttf



    - family: Poppinsbold
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
    - family: Poppinslight
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Light.ttf
        - asset: assets/fonts/Poppins/Poppins-Light.ttf
    - family: Poppinsmedium
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
    - family: Poppinsregular
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
    - family: Poppinssemibold
      fonts:
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
    - family: Poppinsthin
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Thin.ttf
        - asset: assets/fonts/Poppins/Poppins-Thin.ttf